project:
  type: website

# tell quarto to read the generated sidebar
metadata-files:
  - docs/_sidebar.yml

website: 
  navbar:
    background: primary
    search: true
    left:
      - text: "Function References"
        file: docs/index.qmd

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: pyLHD
  parser: google
  dir: docs

  # write sidebar data to this file
  sidebar: docs/_sidebar.yml

  sections:
    - title: Base Designs
      desc: Generate Random LHD
      contents:
        - base_designs.permutations_matrix
        - base_designs.random_lhd
        - base_designs.GLPdesign
    - title: Orthogonal LHD
      desc: Various constructions of orthogonal latin hypercube designs
      contents:
        - OLHD.OLHD_Butler01
        - OLHD.OLHD_Cioppa07
        - OLHD.OLHD_Lin09
        - OLHD.OLHD_Sun10
        - OLHD.OLHD_Ye98
    - title: Criteria
      desc: Space-filling Criterias for LHD
      contents:
        - criteria.AvgAbsCor
        - criteria.coverage
        - criteria.discrepancy
        - criteria.inter_site
        - criteria.MaxAbsCor
        - criteria.maximin
        - criteria.mesh_ratio
        - criteria.MaxProCriterion
        - criteria.phi_p
    - title: Helpers
      desc: miscellaneous utilities for working with LHDs
      contents:
        - helpers.check_bounds  
        - helpers.distance_matrix
        - helpers.eval_design 
        - helpers.OA2LHD               
        - helpers.permute_columns
        - helpers.scale
        - helpers.swap_elements
        - helpers.williams_transform        
