project:
  type: website

# tell quarto to read the generated sidebar
metadata-files:
  - docs/_sidebar.yml

website: 
  navbar:
    background: primary
    search: true
    left:
      - text: "Reference"
        file: docs/index.qmd


quartodoc:
  # the name used to import the package you want to create reference docs for
  package: pyLHD
  parser: google
  dir: docs

  # write sidebar data to this file
  sidebar: docs/_sidebar.yml

  sections:
    - title: Base Designs
      desc: Generate Random LHD
      contents:
        - base_designs.rLHD
        - base_designs.GLPdesign
    - title: Orthogonal LHD
      desc: Various constructions of orthogonal latin hypercube designs
      contents:
        - OLHD.OLHD_Butler01
        - OLHD.OLHD_Sun10
        - OLHD.OLHD_Cioppa07
        - OLHD.OLHD_Ye98
        - OLHD.OLHD_Lin09
    - title: Criteria
      desc: Space-filling Criterias for LHD
      contents:
        - criteria.MaxAbsCor
        - criteria.MaxProCriterion
        - criteria.phi_p
        - criteria.dij
        - criteria.AvgAbsCor
        - criteria.discrepancy
        - criteria.coverage
        - criteria.maximin
        - criteria.mesh_ratio
    - title: Utilities
      desc: miscellaneous utilities for working with LHDs
      contents:
        - utils.exchange
        - utils.williams_transform
        - utils.OA2LHD
        - utils.eval_design
        - utils.adjust_range
        - utils.scale
        - utils.distance_matrix
