site_name: pyLHD Documentation

theme:
  name: "material"


plugins:
  - mkdocstrings


nav:
  - pyLHD Overview: index.md
  - base-designs.md
  - criteria.md
  - LHD-optimize.md
  - OLHD.md
  - utils.md