project:
  type: website

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website: 
  navbar:
    search: true
    left:
      - text: "Overview"
        href: notebooks/intro_pyLHD.ipynb 
      - text: "Reference"
        href: reference/index.qmd

format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: pyLHD
  parser: google

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Base Designs
      desc: Generate Random LHD
      contents:
        - base.LatinSquare
        - base.LatinHypercube
        - base.GoodLatticePoint
    - title: Hadamard Matrices
      desc: Constructions for Hadamard matrices
      contents:
        - hadamard.is_Hadamard
        - hadamard.jacobsthal_matrix
        - hadamard.normalize_hadamard        
        - hadamard.sylvester
        - hadamard.paley
        - hadamard.paley_design
    - title: Maximin LHD
      desc: Algebraic Constructions of Maximim LHD
      contents:
        - maximin.best_linear_permutation
        - maximin.EquidistantLHD
        - maximin.leave_one_out
        - maximin.maximinLHD
    - title: Projection Designs
      desc: Algebraic Constructions for Optimized Projections of LHD
      contents:
        - projections.best_linear_permutation
        - projections.UniformProLHD
    - title: Orthogonal LHD
      desc: Algebraic Constructions of Orthogonal LHD
      contents:
        - orthogonal.OLHD_Butler01
        - orthogonal.OLHD_Cioppa07
        - orthogonal.OLHD_Lin09
        - orthogonal.OLHD_Sun10
        - orthogonal.OLHD_Ye98
        - orthogonal.OA2LHD
    - title: Criteria
      desc: Space-filling and Projection Criterias for LHD
      contents:
        - criteria.Criteria
        - criteria.AvgAbsCor
        - criteria.coverage
        - criteria.discrepancy
        - criteria.LqDistance
        - criteria.MaxAbsCor
        - criteria.MeshRatio
        - criteria.MaxProCriterion
        - criteria.phi_p
        - criteria.UniformProCriterion
    - title: Helpers
      desc: Miscellaneous Utilities for Manipulating LHDs
      contents:
        - helpers.alpha_allowable_perms
        - helpers.are_coprime
        - helpers.axis_combinations        
        - helpers.check_bounds
        - helpers.distance_matrix
        - helpers.euler_phi
        - helpers.generate_primes
        - helpers.generate_prime_powers
        - helpers.is_cyclic
        - helpers.is_prime
        - helpers.is_symmetric
        - helpers.is_skew_symmetric
        - helpers.is_LHD
        - helpers.is_balanced_design
        - helpers.level_permutation
        - helpers.permute_columns
        - helpers.permute_rows
        - helpers.primes_range
        - helpers.replace_values
        - helpers.scale
        - helpers.swap_elements
        - helpers.totatives
        - helpers.verify_generator
        - helpers.WilliamsTransform
        - helpers.zero_base    
