project:
  type: website

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website: 
  navbar:
    search: true
    left:
      - text: "Overview"
        href: notebooks/intro_pyLHD.ipynb 
      - text: "Reference"
        href: reference/index.qmd

format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: pyLHD
  parser: google

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Base Designs
      desc: Generate Random LHD
      contents:
        - base.LatinSquare
        - base.LatinHypercube
        - base.GoodLatticePoint
    - title: Orthogonal LHD
      desc: Various constructions of orthogonal latin hypercube designs
      contents:
        - orthogonal.OLHD_Butler01
        - orthogonal.OLHD_Cioppa07
        - orthogonal.OLHD_Lin09
        - orthogonal.OLHD_Sun10
        - orthogonal.OLHD_Ye98
        - orthogonal.OA2LHD
    - title: Criteria
      desc: Space-filling Criterias for LHD
      contents:
        - criteria.Criteria
        - criteria.AvgAbsCor
        - criteria.coverage
        - criteria.discrepancy
        - criteria.InterSite
        - criteria.pairwise_InterSite
        - criteria.LqDistance
        - criteria.MaxAbsCor
        - criteria.maximin
        - criteria.MeshRatio
        - criteria.MaxProCriterion
        - criteria.phi_p
        - criteria.UniformProCriterion
    - title: Helpers
      desc: miscellaneous utilities for working with LHDs
      contents:
        - helpers.check_bounds
        - helpers.column_combinations
        - helpers.distance_matrix           
        - helpers.is_LHD
        - helpers.is_balanced_design
        - helpers.lapply
        - helpers.permute_columns
        - helpers.permute_rows
        - helpers.replace_values
        - helpers.scale
        - helpers.swap_elements
        - helpers.williams_transform        
