# base_designs.GLPdesign { #pyLHD.base_designs.GLPdesign }

`base_designs.GLPdesign(n_rows, n_columns, h=None, seed=None)`

Good Lattice Point (GLP) Design 

## Parameters

| Name        | Type                                               | Description                                                                                                                                                                                                                                                                       | Default    |
|-------------|----------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `n_rows`    | int                                                | A positive integer specifying the number of rows                                                                                                                                                                                                                                  | _required_ |
| `n_columns` | int                                                | A postive integer specifying the number of columns h (list, optional): A list whose length is same as (n_columns), with its elements that are smaller than and coprime to (n_rows).  Defaults to None. If None, a random sample of (n_columns) elements between 1 and (n_rows-1). | _required_ |
| `seed`      | Optional\[Union\[Integral, np.random.Generator\]\] | If `seed`is an integer or None, a new numpy.random.Generator is created using np.random.default_rng(seed).  If `seed` is already a ``Generator` instance, then the provided instance is used. Defaults to None.                                                                   | `None`     |

## Returns

| Type          | Description                         |
|---------------|-------------------------------------|
| npt.ArrayLike | A (n_rows by n_columns) GLP design. |

## Examples



```{python}
import pyLHD
pyLHD.GLPdesign(n_rows=5,n_columns=3)
```
```{python}
pyLHD.GLPdesign(n_rows=8,n_columns=4,h=[1,3,5,7])
```