# utils.distance_matrix { #pyLHD.utils.distance_matrix }

`utils.distance_matrix(arr, metric='euclidean', p=2)`

Distance matrix based on specified distance measure

## Parameters

| Name     | Type          | Description                                                                                                                                                                                                                                                                                                                                                      | Default       |
|----------|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------|
| `arr`    | numpy.ndarray | A design matrix                                                                                                                                                                                                                                                                                                                                                  | _required_    |
| `metric` | str           | Specifiy the following distance measure:  'euclidean': Usual distance between the two vectors (L_2 norm) 'maximum': Maximum distance between two components of x and y (supremum norm) 'manhattan': Absolute distance between the two vectors (L_1 norm) 'minkowski': The p norm, the pth root of the sum of the pth powers of the differences of the components | `'euclidean'` |
| `p`      | int           | The power of the Minkowski distance. Defaults to 2.                                                                                                                                                                                                                                                                                                              | `2`           |

## Returns

| Type          | Description                                                       |
|---------------|-------------------------------------------------------------------|
| npt.ArrayLike | The calculated distance matrix baed on specified distance measure |

## Examples



```{python}
import pyLHD
random_lhd = pyLHD.random_lhd(n_rows=5,n_columns=3)
pyLHD.distance_matrix(random_lhd)
```
```{python}
pyLHD.distance_matrix(random_lhd, metric = 'manhattan')
```
```{python}
pyLHD.distance_matrix(random_lhd, metric = 'minkowski', p=5)
```