# helpers.WilliamsTransform { #pyLHD.helpers.WilliamsTransform }

`helpers.WilliamsTransform(arr, baseline=0, modified=False)`

Williams Transformation

## Parameters

| Name       | Type                  | Description                                                                              | Default    |
|------------|-----------------------|------------------------------------------------------------------------------------------|------------|
| `arr`      | numpy.numpy.ArrayLike | A numpy ndarray                                                                          | _required_ |
| `baseline` | int                   | A integer, which defines the minimum value for each column of the matrix. Defaults to 0. | `0`        |
| `modified` | (bool, optional)      | Implement modifed version of Williams Transformation. Defaults to False.                 | `False`    |

## Returns

| Type                | Description                                                                                                                                                                                                                                       |
|---------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| numpy.numpy.ndarray | After applying Williams transformation, a matrix whose columns are permutations from {baseline,baseline+1, ..., baseline+(n-1)}. For the modified version. Whenever n is odd, n=2m+1 the columns will be permutations will always be even numbers |

Examples:
```{python}
import pyLHD
x = pyLHD.GoodLatticePoint(size = (7,6))
x
```
Apply Williams Transformation, with `baseline =0` the column level permutations will be (0,1,2,...,6)
```{python}
pyLHD.WilliamsTransform(x)
```
Apply modified Williams Transformation, with `baseline =0` the column level permutations will be (0,2,4,6)
```{python}
pyLHD.WilliamsTransform(x, modified = True)
```