# helpers.swap_elements { #pyLHD.helpers.swap_elements }

`helpers.swap_elements(arr, idx, type='col', seed=None)`

Swap two random elements in a matrix

## Parameters

| Name   | Type                                           | Description                                                                                                                                                                                                                                                            | Default    |
|--------|------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `arr`  | numpy.numpy.ArrayLike                          | A numpy ndarray                                                                                                                                                                                                                                                        | _required_ |
| `idx`  | int                                            | A positive integer, which stands for the (idx) column or row of (arr) type (str, optional):  If type is 'col', two random elements will be exchanged within column (idx). If type is 'row', two random elements will be exchanged within row (idx). Defaults to 'col'. | _required_ |
| `seed` | Optional\[Union\[int, np.random.Generator\]\]) | If `seed`is an integer or None, a new numpy.random.Generator is created using np.random.default_rng(seed).  If `seed` is already a ``Generator` instance, then the provided instance is used. Defaults to None.                                                        | `None`     |

## Returns

| Type                | Description                                    |
|---------------------|------------------------------------------------|
| numpy.numpy.ndarray | A new design matrix after the swap of elements |

Examples:
Choose the first columns of `random_lhd` and swap two randomly selected elements
```{python}
import pyLHD
random_lhd = pyLHD.LatinHypercube(size = (5,3))
random_lhd
```
Choose column 1 of random_lhd and swap two randomly selected elements
```{python}
pyLHD.swap_elements(random_lhd,idx=1,type='col')
```
Choose the first row of random_lhd and swap two randomly selected elements
```{python}
pyLHD.swap_elements(random_lhd,idx=1,type='row')
```