# orthogonal.OLHD_Sun10 { #pyLHD.orthogonal.OLHD_Sun10 }

`orthogonal.OLHD_Sun10(C, r, type='odd')`

Orthogonal Latin Hypercube Design (OLHD). Based on the construction method of Sun et al. (2010)

## Parameters

| Name   | Type   | Description                                                                                                                                                                                                | Default    |
|--------|--------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `C`    | int    | A positve integer.                                                                                                                                                                                         | _required_ |
| `r`    | int    | A positve integer.                                                                                                                                                                                         | _required_ |
| `type` | str    | Run size of design, this can be either odd or even. Defaults to 'odd'. If (type) is 'odd' the run size of the OLHD will be (r*2^(C+1)+1). If (type) is 'even' the run size of the OLHD will be (r*2^(C+1)) | `'odd'`    |

## Returns

| Type          | Description                                                                                                                                        |
|---------------|----------------------------------------------------------------------------------------------------------------------------------------------------|
| npt.ArrayLike | An orthogonal LHD with the following run size: (r*2^(C+1)+1) if type ='odd', or (r*2^(C+1)) if type ='even'. The resulting columns will be (2^(C)) |

## Examples



Create an orthogonal LHD with C=3, r=3, type = 'odd', so n = (3*2^(3+1) )+1 = 49 (rows) and k=2^(3)=8 (columns)
```{python}
import pyLHD
pyLHD.OLHD_Sun10(C=3,r=3,type='odd')
```
Create an orthogonal LHD with C=3, r=3, type = 'even', So n = 3*2^(3+1) = 48 (rows) and k=2^(3)=8 (columns)
```{python}
import pyLHD
pyLHD.OLHD_Sun10(C=3,r=3,type='even')
```